---
# tasks file for ansible-dnscrypt

- name: '[main] Include dnscrypt-proxy install-related tasks'
  include_tasks: install.yml
  tags:
    - dnscrypt

- name: '[main] Include systemd-related tasks, if distro is using systemd init'
  include_tasks: systemd.yml
  when: dnscrypt_systemd.stat.exists
  tags:
    - dnscrypt
    - dnscrypt_systemd

# Modify PIHOLE
- name: '[main] Include pihole-related tasks'
  include_tasks: pihole.yml
  when: dnscrypt_on_pihole
  tags:
    - dnscrypt
    - dnscrypt_pihole
...
